### ISSUE TITLE
iptables error

### ISSUE THREAD

**Issue by cryptedjeffrey** [bubuntux/protorrent#2]
```
> ----------------------------------------------------
> Linux 812526ae798f 5.10.60-qnap #1 SMP Mon Feb 19 12:13:42 CST 2024 x86_64 Linux
> wireguard-tools v1.0.20210914 - https://git.zx2c4.com/wireguard-tools/
> iptables v1.8.10 (nf_tables)
> qBittorrent v4.6.4
> User UID: 1000
> User GID: 1000
> ----------------------------------------------------
> 2024-04-17T13:49:10+00:00 [ERROR] ⛔ ⛔ ⛔ iptables is not functional. Ensure your container config adds --cap-add=NET_RAW ⛔ ⛔ ⛔
> s6-rc: fatal: timed out
```

Installing on a QNAP NAS, running Privileged, when I try to run without privilege I get a wireguard error.

**Comment by bubuntux** [comment]
i think is similar to https://github.com/bubuntux/nordvpn/discussions/202 unfortunately i don't use/have a QNAP NAS to troubleshoot this so good luck

**Comment by cryptedjeffrey** [comment]
It seems that the docker GUI in the QNAP interface does not give the option to add "--cap-add". I've been looking into (or trying) to create a docker compose of this, so I can add the option in the YAML. I'll keep it updated here if I get it working.

**Comment by CherubUltima** [comment]
Did you by any chance find a solution for this problem?
I'm trying to get it running on a Synology NAS and encountered the same problem, even though NET_RAW is active.

**Comment by cryptedjeffrey** [comment]
Nope, gave up on it.
