### ISSUE TITLE
Readme.md environmental variable for group is incorrect

### ISSUE THREAD

**Issue by MattBSG** [bubuntux/protorrent#5]
Hi!

I was diagnosing permission issues with an SMB share which exposed the downloads directory from protorrent when I realized that I had copied the environmental flag `-e GUID=1000` from the readme, but it was incorrect. Looking through the code I see that you utilize `PUID` and `PGID` for users and groups respectively so I updated my container accordingly. Hoping not to come across as pedantic-- I just wanted to flag it to prevent others doing the same as me. Thanks for the work on this repository!

![Screenshot 2024-12-11 163144](https://github.com/user-attachments/assets/0b819d59-a18f-4084-8b68-41771d08bb04)

**Comment by bubuntux** [comment]
fixed thanks
